name: Test Site 1
favicon: null
layout_spectrum: 0.954264156986028
typography_spectrum: 0.20338595216162503
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7092036029789597
  lightness: 0.2317304841708392
  saturation: 0.41676698019728065
  rhythmicContrast: 0.5804908624850214
purpose: []
